# Generated by Django 4.0.2 on 2022-03-24 01:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250, verbose_name='الأسم كامل')),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='رقم الموبيل')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد')),
                ('note', models.TextField(blank=True, null=True, verbose_name='ملحوظه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الأضافه')),
            ],
            options={
                'verbose_name': 'طلب العميل',
                'verbose_name_plural': 'طلبات العميل',
            },
        ),
        migrations.CreateModel(
            name='HomeReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='اسم')),
                ('department', models.CharField(max_length=200, verbose_name='وصف الشخص عميل او موظف')),
                ('description', models.TextField(verbose_name='الوصف')),
            ],
            options={
                'verbose_name': 'ريفيوا',
                'verbose_name_plural': 'ريفيوهات عملاء',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name_in_inglish', models.CharField(max_length=200, unique=True, verbose_name='اسم المنتج بالانجليزي')),
                ('product_name_in_arabic', models.CharField(max_length=200, unique=True, verbose_name='اسم المنتج بالعربي')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='اسم المنتج في الرابط')),
                ('description', models.TextField(blank=True, verbose_name='الوصف بالإنجليزي')),
                ('descriptionin_arabic', models.TextField(blank=True, verbose_name=' الوصف بالعربي')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='السعر')),
                ('is_price', models.BooleanField(default=False, verbose_name='إظهار السعر؟')),
                ('images', models.ImageField(upload_to='', verbose_name='الصوره')),
                ('is_available', models.BooleanField(default=True, verbose_name='متوفر؟')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الأضافه')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='اخر تعديل')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
            options={
                'verbose_name': 'المنتج',
                'verbose_name_plural': 'المنتجات',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='', verbose_name='الصوره')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الأضافه')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='اخر تعديل')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
            options={
                'verbose_name': 'صورة المنتج',
                'verbose_name_plural': 'صور المنتجات',
            },
        ),
    ]
