# Generated by Django 4.0.2 on 2022-03-08 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'المنتج', 'verbose_name_plural': 'المنتجات'},
        ),
    ]
