# Generated by Django 4.0.2 on 2022-03-24 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tesst',
            field=models.BooleanField(default=True, verbose_name='توفر؟'),
        ),
    ]
