# Generated by Django 4.0.2 on 2022-03-08 23:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250, verbose_name='الأسم كامل')),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='رقم الموبيل')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الأضافه')),
            ],
            options={
                'verbose_name': 'طلب العميل',
                'verbose_name_plural': 'طلبات العميل',
            },
        ),
    ]
