# Generated by Django 4.0.2 on 2022-03-24 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_price',
            field=models.BooleanField(default=False, verbose_name='إظهار السعر؟'),
        ),
    ]
