# Generated by Django 4.0.2 on 2022-03-24 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_is_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tesst',
        ),
    ]
