# Generated by Django 4.0.2 on 2022-03-09 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_customerrequests_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='اسم')),
                ('department', models.CharField(max_length=200, verbose_name='وصف الشخص عميل او موظف')),
                ('description', models.TextField(verbose_name='الوصف')),
            ],
            options={
                'verbose_name': 'ريفيوا',
                'verbose_name_plural': 'ريفيوهات عملاء',
            },
        ),
    ]
