# Generated by Django 4.0.2 on 2022-03-27 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_product_tesst'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tesst',
        ),
    ]
