# Generated by Django 4.0.2 on 2022-08-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_product_tesst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='الوصف بالإنجليزي'),
        ),
        migrations.AlterField(
            model_name='product',
            name='descriptionin_arabic',
            field=models.TextField(blank=True, null=True, verbose_name=' الوصف بالعربي'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name_in_arabic',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='اسم المنتج بالعربي'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name_in_inglish',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='اسم المنتج بالانجليزي'),
        ),
    ]
