# Generated by Django 4.0.2 on 2022-03-09 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_homereviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='descriptionin_arabic',
            field=models.TextField(blank=True, verbose_name=' الوصف بالعربي'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='الوصف بالإنجليزي'),
        ),
    ]
