# Generated by Django 4.0.2 on 2022-08-04 10:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name_in_arabic',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, unique=True, verbose_name='اسم المنتج بالعربي'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name_in_inglish',
            field=models.CharField(default=datetime.datetime(2022, 8, 4, 10, 55, 26, 985052, tzinfo=utc), max_length=200, unique=True, verbose_name='اسم المنتج بالانجليزي'),
            preserve_default=False,
        ),
    ]
