# Generated by Django 4.0.2 on 2022-03-24 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSliedes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='العنوان')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('slide_image', models.ImageField(upload_to='', verbose_name='صوره')),
            ],
            options={
                'verbose_name': 'الصفحة الرئيسية',
                'verbose_name_plural': 'صور الصفحة الرئيسية',
            },
        ),
        migrations.CreateModel(
            name='MasterCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name_inenglish', models.CharField(max_length=255, unique=True, verbose_name='اسم القسم بالانجليزي')),
                ('category_name_inarabic', models.CharField(max_length=255, unique=True, verbose_name='اسم القسم بالعربي')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='اسم القسم في الرابط')),
                ('description', models.TextField(blank=True, max_length=255, verbose_name='الوصف')),
                ('cat_image', models.ImageField(blank=True, upload_to='', verbose_name='صوره لو في')),
            ],
            options={
                'verbose_name': 'القصم الرئيسي',
                'verbose_name_plural': 'الأقسام الرئيسيه',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name_inenglish', models.CharField(max_length=255, unique=True, verbose_name='اسم القسم بالانجليزي')),
                ('category_name_inarabic', models.CharField(max_length=255, unique=True, verbose_name='اسم القسم بالعربي')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='اسم القسم في الرابط')),
                ('description', models.TextField(blank=True, max_length=255, verbose_name='الوصف')),
                ('cat_image', models.ImageField(blank=True, upload_to='', verbose_name='صوره لو في')),
                ('master_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.mastercategory')),
            ],
            options={
                'verbose_name': 'القسم',
                'verbose_name_plural': 'الأقسام',
            },
        ),
    ]
