# Generated by Django 4.0.2 on 2022-02-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name_inenglish', models.CharField(max_length=255, unique=True, verbose_name='اسم القسم بالانجليزي')),
                ('category_name_inarabic', models.CharField(max_length=255, unique=True, verbose_name='اسم القسم بالعربي')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='اسم القسم في الرابط')),
                ('description', models.TextField(blank=True, max_length=255, verbose_name='الوصف')),
                ('cat_image', models.ImageField(blank=True, upload_to='photos/categories', verbose_name='صوره لو في')),
            ],
            options={
                'verbose_name': 'القسم',
                'verbose_name_plural': 'الأثسام',
            },
        ),
    ]
