# Generated by Django 4.0.2 on 2022-03-24 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name_inenglish', models.CharField(max_length=255, unique=True, verbose_name='اسم القسم بالانجليزي')),
                ('category_name_inarabic', models.CharField(max_length=255, unique=True, verbose_name='اسم القسم بالعربي')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='اسم القسم في الرابط')),
                ('description', models.TextField(blank=True, max_length=255, verbose_name='الوصف')),
                ('cat_image', models.ImageField(blank=True, upload_to='', verbose_name='صوره لو في')),
            ],
            options={
                'verbose_name': 'القصم الرئيسي',
                'verbose_name_plural': 'الأقسام الرئيسيه',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='master_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.mastercategory'),
        ),
    ]
