# Generated by Django 4.0.2 on 2022-08-03 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name_inarabic',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='اسم القسم بالعربي'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name_inenglish',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='اسم القسم بالانجليزي'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='homesliedes',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='mastercategory',
            name='category_name_inarabic',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='اسم القسم بالعربي'),
        ),
        migrations.AlterField(
            model_name='mastercategory',
            name='category_name_inenglish',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='اسم القسم بالانجليزي'),
        ),
        migrations.AlterField(
            model_name='mastercategory',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='الوصف'),
        ),
    ]
