# Generated by Django 4.0.2 on 2022-03-08 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSliedes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='العنوان')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('slide_image', models.ImageField(upload_to='photos/slide_view', verbose_name='صوره')),
            ],
            options={
                'verbose_name': 'الصفحة الرئيسية',
                'verbose_name_plural': 'صور الصفحة الرئيسية',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'القسم', 'verbose_name_plural': 'الأقسام'},
        ),
    ]
