# Generated by Django 4.0.2 on 2022-03-24 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_mastercategory_category_master_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='master_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='category.mastercategory'),
            preserve_default=False,
        ),
    ]
