# Generated by Django 4.0.2 on 2022-08-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_category_name_inarabic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name_inarabic',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم القسم بالعربي'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name_inenglish',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم القسم بالانجليزي'),
        ),
    ]
